dist: xenial
branches:
  only:
  - master
  - develop
language: node_js
node_js: '10'
cache:
  directories:
  - node_modules
jobs:
  include:
  - script:
    - cd Nasa-Test && npm install && npm run lint && npm run build && npm run test
    name: Build Outreach-Interviews
stages:
- test
notifications:
  slack:
    secure: xhuIPz8DpmBhgivWajgpB0crqv67ltbihIaFuW0lPOVHp5L7kmd/pwE1yS4ncR7dNrh622yaxEKuLsGL4zX2Va1JbcifDy9VxRajErVmZiGUEedblddSZACE7DdVAk0xmvNQxdmPeCKggx0MeErvSOeW9GzqmLAWPXHn9Fo1j4VZ8+xXVlQnNcMvVzARtKB5ndwsJOKH/MGM71MD6ZpfaV2lrVISMuJyKAl6btWdwuGS6WhjwK5b4vv7FGHw19lRJwQiJQcOiEnIlnjKU4Alg1x+j7aOk66vBwO2DBc/+fs2fAFr1fD1Huie/3poXiHELJRf3P5vMAeYzoWJ0bVDOvJMduGQeQBTarJYvN647O4lOz/q0Ehe7hxcKAuPrYSeIOjt7ejTX+Mcx2B6dEqZMDX530l14LBlakNlJ64os+Df8YmD5T3Ea2OkueUuoX/xq9fZK+KyxIN1G34I8RHw3bf5npomS6xyyzY8lOpgWgm//zr3Geu79RUZAVWL6luV8uPJvlj5qiyZz+GUggXzclxpSVbzhfDw9bvZl07kztpDRb3UDtX3HgIiU6dIZ6WjNUrqMfovVADO+3tk/2cMwS8oL5yiu7U409oKM/C15P2HckVbUSiDzxjt6N/CG6a/pcthwDX+N7lK8T7GFBmhmkQwEm5AkCJD/LmSqtOiG5Y=
env:
  global:
    secure: MI+D3YsnGaiJvcaF5eoj/1mx83OWoNl/XvY38WIKJNpORNq8l8HuhGD1qZwAXVS6zzuzd0Jb9aD7KZFKoeDY3gClbCb6fVL1x2IkwlldYaGPFdI4cLTz5cYkbuI8exs04DjbiEy41rrfMzaTABQRVYGMGPYyS3RDNDmhczOTClCcHmwxwsGrcDU2pRczZPpL4tpPa38ek7zW1MDCYoZEh9BbjRzKHmrrR7zKWjopZXWEJhKTUrWfiOk15vqfcgJ4qAeeL9oz0I0TYH6KSIeW13+zNrq+LEnO3S+w24pOLHGfhqQG/xrJjshPo8GrVCAbJmMUJwZ9Gv/bLLz8YtHFNHBuDijB9MDsHJ7q92CB3fu6QOm4UKW2p1iZymHh+ewduyETLFeMgFe4Kr6KxYj2bCeIaeMSQjcMm+jXuUV9rT7/JN0y77G32tDwAAGaQ9q070xJcsxZKO1DNO8rIeh2+M6+/LGYHqRJ9OB3z0xu4LtoaKP2zj2xoipSQ9mB7agQX4Rjt0vc0egHtK2CVrE35tg3ZEH+x10MElxxdAvPibGnIYSRaR+6PQFINYJrNa3nbu8FM8DPmWy2kQSADMcVGg8WoSl7KM9Q0HzCceL+lYKn7WoIkYq+TbtgsEYMSw/+iHSxyMAGFsA8us6GDat5ByMaSiBs50Suxwo65FAApsE=
